service: winston-export
app: winston-export
org: akamaidigital
frameworkVersion: '3'

useDotenv: true

package:
  individually: true
  include:
    - 'integrations/*'

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:PutsObject
          Resource:
            - arn:aws:s3:::winstonexport/*
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - arn:aws:ses:us-east-1:946184463079:identity/thomas@getakamai.com
  environment:
    username: ${env:USERNAME}
    password: ${env:PASSWORD}
    winston: ${env:DUOPLANE_WINSTON}

functions:
  export:
    handler: handler.export
    memorySize: 1600
    timeout: 60
    events:
      - schedule: cron(0 21 * * ? *)

  email:
    handler: handler.email
    memorySize: 128
    timeout: 60
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:946184463079:winstonExport-export
